server:
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH:/}
  port: ${SERVER_PORT}

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${DATABASE}?serverTimezone=UTC&allowMultiQueries=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}
  redis:
    host: 127.0.0.1
    # redis服务器地址
    port: 6379
    # 默认端口就是6379 可不配置
    #password:  # redis服务器连接密码（默认为空）
    database: 0
    #使用Redis0号库
    jedis:
      pool:
        max-active: 8
        # 连接池最大连接数（如果配置为<=0，则没有限制）

mybatis-plus:
  type-aliases-package: ${ENTITY_PATH}
  mapper-locations: ${MAPPER_PATH}

logging:
  level:
    com.kang: DEBUG
    org.springframework.boot.autoconfigure: error
  config: classpath:logback-boot.xml
